displayName: Recognyze Botwall Plugin
type: middleware
import: github.com/recognyze-ai/traefik-bot-wall
iconPath: .assets/recognyze-logo.png

summary: Recognyze botwall middleware plugin evaluates incoming requests against Recognyze bot rules and allows or blocks traffic before it reaches your upstream service.

testData:
  botRulesFile: fixtures/botdef.json
  botRulesURL: disabled
  cacheTTL: 24h
  refreshBeforeExpiry: 1h
